plugins:
  memberships_enabled:
    default: true
    client: true

procourse_memberships:
  memberships_go_live:
    default: false
    client: true
  memberships_contact_user:
    default: ''
    type: username
  memberships_currency:
    client: true
    type: enum
    default: "USD"
    choices:
      - "CAD"
      - "EUR"
      - "GBP"
      - "USD"
  memberships_gateway:
    client: true
    type: enum
    default: "Braintree"
    choices:
      - "Braintree"
      - "PayPal"
      - "Stripe"
      - "Test"
  memberships_include_paypal:
    default: false
    client: true
  memberships_paypal_username:
    default: ""
    client: false
  memberships_paypal_password:
    default: ""
    client: false
  memberships_paypal_signature:
    default: ""
    client: false
  memberships_braintree_merchant_id:
    default: ""
    client: false
  memberships_braintree_public_key:
    default: ""
    client: false
  memberships_braintree_private_key:
    default: ""
    client: false
  memberships_paypal_api_id:
    default: ""
    client: false
  memberships_paypal_api_secret:
    default: ""
    client: false
  memberships_stripe_publishable_key:
    default: ""
    client: true
  memberships_stripe_secret_key:
    default: ""
    client: false
  memberships_stripe_webhook_secret:
    default: ""
    client: false
